### ISSUE TITLE
Installing SpecStory from the VSCode Marketplace doesn't install it into Cursor

### ISSUE THREAD

**Issue by jakelevirne** [specstoryai/getspecstory#8]
from Arturo:
Congrats on the first launch! — Need help 😊. I Installed the extension in VS Code:
![image](https://github.com/user-attachments/assets/177527f8-d901-44f8-b7eb-340ddd71cf31)

… I can see it here (in VSCode):
![image](https://github.com/user-attachments/assets/fae5bd3d-07be-4ede-8b8c-24bc5e4c3684)

… but I don’t see it in Cursor. Tried restarting both but now… any tips?
![image](https://github.com/user-attachments/assets/8fd18741-0f0d-4d7b-90e4-c215c5cd7a0e)

**Comment by jakelevirne** [comment]
**Workaround**

From the marketplace, it will install into VSCode by default but not into cursor =( ... we have to find a way to make this experience better.  Here's what you can do:

Open Cursor

Click the Extensions icon in the upper left:
![image](https://github.com/user-attachments/assets/9da5e6ec-5137-41a8-bdcb-5d0b6578031a)

Type "SpecStory" into the search, then click Install:
![image](https://github.com/user-attachments/assets/d5846cde-0717-4da0-834c-4cd5c4678333)

**Comment by belucid** [comment]
We've added lots of mentions of how to install into Cursor in the extension README and docs, so this should be a lot more clear now.
