### ISSUE TITLE
"Failed to generate SpecStory" when trying to save composer history

### ISSUE THREAD

**Issue by lkonga** [specstoryai/getspecstory#9]
Cursor version: 0.42.5
OS: Linux

---

Getting this error when trying to save composer history:
```
# Error

Failed to generate SpecStory: TypeError: Cannot read properties of undefined (reading 'map')
```

**Comment by gregce** [comment]
Hi @lkonga, the extension is not presently backwards compatible with all versions of Cursor. It has been tested to work with `Cursor Version: 0.43.6` which is [current](https://www.cursor.com/changelog/new-composer-ui-agent-commit-messages). Versions of Cursor prior to `0.43.5` stored chat and composer data in a way on disk that has significantly changed.

If you're willing to upgrade to the most recent version of Cursor, we'd love if you could try it and let us know your feedback.

Apologies for this!

**Comment by belucid** [comment]
We added mentions in the docs about the required version of Cursor.
